keycloak:
  auth-server-url: https://fhir.curemd.com:4334/
  realm: testing
  resource: test
  credentials:
    secret: g0Z2bIgiDs2BB18HsYbD5DnfxKUYoX4w
  ssl-required: external
  bearer-only: true

spring:
  main:
    allow-circular-references: true
  